### ISSUE TITLE
[PROPOSAL] [chimera-sched] Add filename configuration parameter

### ISSUE THREAD

**Issue by wschoenell** [astroufsc/chimera#104]
Scheduler filenames are hardcoded to be OBJNAME-TIME-DATE. See below.

The proposal here is to have a config directive which tells the scheduler the filename format to be used.

	  - type: Scheduler
		name: sched
		filename: ${OBJNAME}-${DATE}-${TIME}
		algorithm: Sequential
		autofocus: /Autofocus/autofocus
		...

https://github.com/astroufsc/chimera/blob/065ccfed7e11d5b68e64fc4f8aee185a511b0a2f/src/scripts/chimera-sched#L195-L202

**Comment by tribeiro** [comment]
I think it's just a matter of including the possibility of changing the
header in chimera-sched. The scheduler itself accepts configuration via the
database.

Em sexta-feira, 4 de setembro de 2015, William Schoenell <
notifications@github.com> escreveu:

> Scheduler filenames are hardcoded to be OBJNAME-TIME-DATE. See below.
>
> The proposal here is to have a config directive which tells the scheduler
> the filename format to be used.
>
>   - type: Scheduler
>     name: sched
>     filename: ${OBJNAME}-${DATE}-${TIME}
>     algorithm: Sequential
>     autofocus: /Autofocus/autofocus
>     ...
>
>
> https://github.com/astroufsc/chimera/blob/065ccfed7e11d5b68e64fc4f8aee185a511b0a2f/src/scripts/chimera-sched#L195-L202
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/astroufsc/chimera/issues/104>.
>


-- 
Sent from Mobile

**Comment by wschoenell** [comment]
Yeap... Better to put an option to `chimera-sched` like `-o ${OBJ}-${DATE}-${TIME}$, which would have the same behavior of `chimera-cam`

**Comment by tribeiro** [comment]
Yeap!

Em sábado, 5 de setembro de 2015, William Schoenell <
notifications@github.com> escreveu:

> Yeap... Better to put an option to chimera-sched like -o
> ${OBJ}-${DATE}-${TIME}$, which would have the same behavior ofchimera-cam`
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/astroufsc/chimera/issues/104#issuecomment-137993447>.
>


-- 
Sent from Mobile
