### ISSUE TITLE
Improve the way instruments capabilities are checked

### ISSUE THREAD

**Issue by wschoenell** [astroufsc/chimera#124]
This discussion started here: https://github.com/astroufsc/chimera/pull/116#discussion_r42886350

We now have only on Camera and Focuser instruments a method `supports` with the supported characteristics, like this in the camera interface:
https://github.com/astroufsc/chimera/blob/f67ad3aa0c301feb651462ef8a5bd81d33edeb99/src/chimera/instruments/fakecamera.py#L342-L343
where the possible supported characteristics of the hardware are defined on an enum like this:
https://github.com/astroufsc/chimera/blob/f67ad3aa0c301feb651462ef8a5bd81d33edeb99/src/chimera/interfaces/camera.py#L38-L43

This approach now is being used ONLY for displaying the capabilities on the chimera scripts.

For the dome, telescope and others we are doing the checks with try/except approach. If the method is not implemented, a `NotImplementedError` exception is raised and treated.

If I understood right from the mentioned discussion, a better way to implement this could be to define a method, like `supports` from camera which returns if `self` is an instance or not of an interface class.

For example:
```python
if telescope.supports(interfaces.telescope.TelescopeCover):
    print "Telescope supports Open/Close cover"
```

So, all instruments must have a `supports` method with:
```python
def supports(self, feature):
    return isinstance(self, feature)
```

And, finally, the `CameraFeature` and `FocuserFeature` would be removed from the corresponding interfaces.

**Comment by wschoenell** [comment]
One change that would be necessary is to clean all the base methods (see `TelescopeBase` example below) to not inherit all the Telescope sub-classes, but only the ones that are mandatory. In the `TelescopeBase` example, I would make mandatory only the `TelescopeSlew`.

https://github.com/astroufsc/chimera/blob/cb56cebfabd28937f8448161d7f0d917f410bf88/src/chimera/instruments/telescope.py#L39-L42

**Comment by tribeiro** [comment]
I was wondering, since the ``supports`` function should be common to all instruments and controllers, isn't it best to implement it at the ``ChimeraObject`` level?
