### ISSUE TITLE
openSlit on scheduler PointHandler

### ISSUE THREAD

**Issue by tribeiro** [astroufsc/chimera#129]
In here:

https://github.com/astroufsc/chimera/blob/1a27558c2f15e9c078088220fb6c7c33b38394b1/src/chimera/controllers/scheduler/handlers.py#L49

Do we really want the PointHandler on the scheduler constantly opening the dome? For example, when doing dome flats this is undesired, to say the least.

**Comment by wschoenell** [comment]
I think that we should remove this even for safety reasons. I prefer the scheduler being taking pictures with the dome closed due a bug than a wet telescope due a scheduler action of opening the dome in a wrong time.

**Comment by tribeiro** [comment]
Exactly...
