### ISSUE TITLE
Possible source of memory leak on chimera

### ISSUE THREAD

**Issue by tribeiro** [astroufsc/chimera#164]
I think this issue may be somewhat related to #160. 

I'm investigating a memory leak on the t80cam driver and I think the source of it is actually on chimera itself (or the library chimera uses to open fits files, astropy.io.fits). More specifically in the imageserver controller.

For instance, the imageserver works by adding an unrestricted number of fits files to its catalog. For each image it stores a chimera_id, filename and http address as well as an opened version of the file itself.

As it is right now, when we finish an exposure with the chimera-cam, the script closes the fits file at the end. When using the scheduler (or any other controller that takes images), this is left unchecked (hence issue #160). 

I tried closing this files on my camera driver but, for some mysterious reason, it seems like the fits files keeps occupying memory. I tried garbage collecting them with no avail. 

But,I could sort of find a workaround to this problem by limiting the number of images on the imageserver database. This doesn't seem to complete get rid of the memory leak problem, but does mitigate it in some way. For instance, without that I cannot reach 300 bias frames on the t80cam driver. And limiting the number of images on the imageserver database to 10 I could get to 300 bias, though occupied memory was still increasing. So, I guess there must be another leak somewhere. 

The solution I implemented was to add this:

```python 
            if len(self.imagesByID) > self['max_images']:
                remove_items = []
                for item in self.imagesByID:
                    remove_items.append(item)

                for item in remove_items:
                    self.log.debug('Unregistering image %s' % item)
                    self.unregister(self.imagesByID[item])
                    if len(self.imagesByID) < self['max_images']:
                        break

```

to 

https://github.com/astroufsc/chimera/blob/master/src/chimera/controllers/imageserver/imageserver.py#L72

I will improve that a little bit and keep working on finding the source of the other leak (?). Any idea will be welcome!

**Comment by agati** [comment]
I solved an apparently similar problem in another project explicitly deleting the list or the array after it has been  used.
del M; //where M={} or M=[]
