### ISSUE TITLE
[PROPOSAL] Hexapod control TS-83

### ISSUE THREAD

**Issue by tribeiro** [astroufsc/chimera#26]
Include secondary mirror hexapod control on chimera. Most modern technology telescopes comes with hexapod-based secondary mirror extending the control over optical alignment and focus. The idea is to be able to control hexapod position (x,y,z,v,w) from chimera. 

Note that, in this context, z is equal to focus position in standard telescopes. Therefore, my suggestion would be to extend chimera-focus to include the other coordinates (x,y,v,w). 

chimera-focus
============

Autofocus:

    --auto              Start an autofocus session using the selected
                        parameters. You can select a focuser range and the
                        size of the step for the sequence. This option is
                        exclusive, you cannot move manually at the same time.
    --disable-display   Disable interactive display during autofocus
    --filter=AUTOFOCUS_FILTER
                        Which filter to use in the autofocus run. [default
                        =use-current-filter]
    --range=START-END   Defines autofocus focuser range to be covered (z-range if hexapod). Use
                        start-end, as in 1000-6000 to run from 1000 to 6000. 
                        [default=1000-6000]
    --xrange=START-END   Defines autofocus focuser range to be covered in the x-axis. Use
                        start-end, as in 1000-6000 to run from 1000 to 6000. 
                        [default=1000-6000]
    --yrange=START-END   Defines autofocus focuser range to be covered in the y-axis. Use
                        start-end, as in 1000-6000 to run from 1000 to 6000. 
                        [default=1000-6000]
    --vrange=START-END   Defines autofocus focuser angle range to be covered around x-axis. Use
                        start-end, as in -10+10 to run from -10 to +10. 
                        [default=-10+10]
    --wrange=START-END   Defines autofocus focuser angle range to be covered around y-axis. Use
                        start-end, as in -10+10 to run from -10 to +10. 
                        [default=-10+10]
    -t EXPTIME, --exptime=EXPTIME
                        Defines autofocus frame exposure time. [default=10.0]
    --debug=PREVIOUS_RUN_DIR
                        Run an autofocus debug session using data from
                        PREVIOUS_RUN_DIR.
    --step=STEP         Defines autofocus step (z-step if hexapod). [default=500]
    --xstep=STEP        Defines autofocus step in x-axis. [default=500]
    --ystep=STEP        Defines autofocus step in y-axis. [default=500]
    --vstep=STEP        Defines autofocus step in rotation with respect to x-axis. [default=1]
    --wstep=STEP        Defines autofocus step in rotation with respect to x-axis. [default=1]

Commands:

    -i, --info          Print focuser current information
    -z, --zstep=N              Move N steps in z axis (positive or negative)
    --zto=POSITION       Move z-axis to POSITION
    -x, --xstep=N              Move N steps in x axis (positive or negative)
    --xto=POSITION       Move x-axis to POSITION
    -y, --ystep=N              Move N steps in y axis (positive or negative)
    --yto=POSITION       Move y-axis to POSITION
    --vrot=D              Rotate D degrees with respect to x-axis (positive or negative)
    --vto=POSITION       Rotate to POSITION (degrees) with respect to x-axis
    --wrot=D              Rotate D degrees with respect to y-axis (positive or negative)
    --wto=POSITION       Rotate to POSITION (degrees) with respect to y-axis

**Comment by wschoenell** [comment]
Fix being discussed on #117
