### ISSUE TITLE
astelco telescope and dome issue

### ISSUE THREAD

**Issue by tribeiro** [astroufsc/chimera#28]
While using as telco telescope module, chimera is completely unaware of the dome. Since the telescope moves much faster than the dome, it happens sometime that the telescope is ready while the dome is not. But chimera thinks it is all ready.

**Comment by tribeiro** [comment]
Maybe implement and astelcodome would solve this issue?

**Comment by phsilva** [comment]
Dont' think astelcodome will solve because it will use a different TPL connection, so telescope will still die.

**Comment by phsilva** [comment]
yes, chimera-cam cam wait until dome is in sync. no dome, no sync.

**Comment by phsilva** [comment]
even more, the basic logic on ImageRequest have dome sync option, so every one asking for image can have dome synced image. So we need a dome for astelco if we need to sync.

**Comment by nsaavedra-naircl** [comment]
Doesn't astelos have some "dome follow" option we can turn on from chimera?
I seem to have heard the prussian guys talk about it...

On Fri, Jan 23, 2015 at 12:01 PM, Paulo Henrique Silva <
notifications@github.com> wrote:

> even more, the basic logic on ImageRequest have dome sync option, so every
> one asking for image can have dome synced image. So we need a dome for
> astelco if we need to sync.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/astroufsc/chimera/issues/28#issuecomment-71205281>.
>



-- 
Nelson Saavedra Pinos
------------------------------------------------
NAIR Servicios Informáticos E.I.R.L.
------------------------------------------------
e: saavedra.nelson@gmail.com
c: +56 51 69074027

**Comment by phsilva** [comment]
Yes, they do, that's the option astelcodome will use. But this should be in a dome module not in the telescope itself I think.

**Comment by nsaavedra-naircl** [comment]
Sure, sounds more logical to tell the dome to follow the telescope, and not
the other way around! ;-)

On Fri, Jan 23, 2015 at 12:59 PM, Paulo Henrique Silva <
notifications@github.com> wrote:

> Yes, they do, that's the option astelcodome will use. But this should be
> in a dome module not in the telescope itself I think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/astroufsc/chimera/issues/28#issuecomment-71214739>.
>



-- 
Nelson Saavedra Pinos
------------------------------------------------
NAIR Servicios Informáticos E.I.R.L.
------------------------------------------------
e: saavedra.nelson@gmail.com
c: +56 51 69074027

**Comment by tribeiro** [comment]
Done gentleman! The basic functionality are implemented and it works beautifully! It was a little bit hard to override the chimera behaviour with respect to the dome. I subclassed the control function so it only flushes the queue. The slewToAz function is still not finished. Right now, if the dome is in track mode it will check if Dome and Telescope are aligned. If yes, then finishes. If not wait until it is... Still don't know how to change the dome position manually. Tried several things. Opening and Closing the slit is already implemented. I will clean the code before submitting. 

Cheers,

T.

**Comment by ankanaan** [comment]
great.

just to clarify: slewToAz is what you would like to use for dome flats for
instance, right?

to track the telescope we should use astelos's functionality, I suppose.(?)

cheers,

Antonio

**Comment by tribeiro** [comment]
Yes and yes... I am still working on slewToAz so we can move the dome at will. The procedure will be to put the telescope on parking mode and than we can move the dome. It the dome is in track mode it is handled completely by astelos.

**Comment by ankanaan** [comment]
closed means solved and closed or abandoned and closed ? :-)

**Comment by tribeiro** [comment]
Solved and closed... :) 

Sent from mobile

> Em 27/02/2015, às 08:59, Antonio Kanaan <notifications@github.com> escreveu:
> 
> closed means solved and closed or abandoned and closed ? :-)
>
