### ISSUE TITLE
[ASTELCO] driver does not move by offsets (jogging)

### ISSUE THREAD

**Issue by wschoenell** [astroufsc/chimera#34]
These options are not working on chimera-tel. They just do not do anything when called.

    chimera-tel --help
        ...
    -N ARCSEC, --move-north=ARCSEC
     Move telescope ARCSEC arcseconds to North.
     -S ARCSEC, --move-south=ARCSEC
     Move telescope ARCSEC arcseconds to South.
     -E ARCSEC, --move-east=ARCSEC
     Move telescope ARCSEC arcseconds to East.
     -W ARCSEC, --move-west=ARCSEC
     Move telescope ARCSEC arcseconds to West.
          ...

**Comment by tribeiro** [comment]
This is fixed in latest astelco drivers.
