### ISSUE TITLE
Repository cleanup TS-102

### ISSUE THREAD

**Issue by wschoenell** [astroufsc/chimera#35]
Remove unused / not working modules.
  - Cherrypy
  - webadmin module
  - gui module

**Comment by ankanaan** [comment]
when you remove an unused module where does it go?  heaven? limbo? hell?

the reason I ask is that we may ressurrect some of these things in the
future.  For instance, we talked about using the webadmin module, or
something similar to it, to close the dome in the future.

The idea is to have the 4m operator issue some sort of broadcast signal in
the ctio network informing all telescopes that the 4m is being closed due
to weather conditions.

We are going in a new direction with the GUI, still it is important to keep
some copy of it, just in case.

A

**Comment by wschoenell** [comment]
Everything that you do on git you can rollback whenever you want. It stays
on the commits history.

**Comment by ankanaan** [comment]
my worry is that this disappears into history and unless somebody remembers
it existed someday and knows what it was called we will end up redoing
these things in case we need them.  Makes sense?

**Comment by nsaavedra-naircl** [comment]
If we do it properly, every change, including trips to the beyond, is kept
in git's history log. Very cool, it also forces developers to be careful
about commiting stuf that mau embarass them in the future!

On Thu, Feb 26, 2015 at 10:39 AM, William Schoenell <
notifications@github.com> wrote:

> Everything that you do on git you can rollback whenever you want. It stays
> on the commits history.
>
> On Thu, Feb 26, 2015 at 2:02 PM Antonio Kanaan <notifications@github.com>
> wrote:
>
>
> > when you remove an unused module where does it go? heaven? limbo? hell?
> >
> > the reason I ask is that we may ressurrect some of these things in the
> > future. For instance, we talked about using the webadmin module, or
> > something similar to it, to close the dome in the future.
> >
> > The idea is to have the 4m operator issue some sort of broadcast signal
> in
> > the ctio network informing all telescopes that the 4m is being closed due
> > to weather conditions.
> >
> > We are going in a new direction with the GUI, still it is important to
> keep
> > some copy of it, just in case.
> >
> > A
> >
> > On Tue, Feb 24, 2015 at 11:46 AM, William Schoenell <
> > notifications@github.com> wrote:
> >
> > > Remove unused / not working modules.
> > >
> > > - Cherrypy
> > > - webadmin module
> > > - gui module
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/astroufsc/chimera/issues/35>.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/astroufsc/chimera/issues/35#issuecomment-76174204>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/astroufsc/chimera/issues/35#issuecomment-76179026>.
>



-- 
Nelson Saavedra Pinos
------------------------------------------------
NAIR Servicios Informáticos E.I.R.L.
------------------------------------------------
e: saavedra.nelson@gmail.com
c: +56 51 69074027

**Comment by nsaavedra-naircl** [comment]
You can look at who did what since the beginning of (git) times

On Thu, Feb 26, 2015 at 10:42 AM, Antonio Kanaan <notifications@github.com>
wrote:

> my worry is that this disappears into history and unless somebody remembers
> it existed someday and knows what it was called we will end up redoing
> these things in case we need them. Makes sense?
>
> On Thu, Feb 26, 2015 at 10:39 AM, William Schoenell <
>
> notifications@github.com> wrote:
>
> > Everything that you do on git you can rollback whenever you want. It
> stays
> > on the commits history.
> >
> > On Thu, Feb 26, 2015 at 2:02 PM Antonio Kanaan <notifications@github.com
> >
> > wrote:
> >
> > > when you remove an unused module where does it go? heaven? limbo? hell?
> > >
> > > the reason I ask is that we may ressurrect some of these things in the
> > > future. For instance, we talked about using the webadmin module, or
> > > something similar to it, to close the dome in the future.
> > >
> > > The idea is to have the 4m operator issue some sort of broadcast signal
> > in
> > > the ctio network informing all telescopes that the 4m is being closed
> due
> > > to weather conditions.
> > >
> > > We are going in a new direction with the GUI, still it is important to
> > keep
> > > some copy of it, just in case.
> > >
> > > A
> > >
> > > On Tue, Feb 24, 2015 at 11:46 AM, William Schoenell <
> > > notifications@github.com> wrote:
> > >
> > > > Remove unused / not working modules.
> > > >
> > > > - Cherrypy
> > > > - webadmin module
> > > > - gui module
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/astroufsc/chimera/issues/35>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/astroufsc/chimera/issues/35#issuecomment-76174204
> >.
> >
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/astroufsc/chimera/issues/35#issuecomment-76179026>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/astroufsc/chimera/issues/35#issuecomment-76179430>.
>



-- 
Nelson Saavedra Pinos
------------------------------------------------
NAIR Servicios Informáticos E.I.R.L.
------------------------------------------------
e: saavedra.nelson@gmail.com
c: +56 51 69074027

**Comment by nsaavedra-naircl** [comment]
this is why I was able to recover everything I messed up during the Great
Git Catastrophe... except what I never had a chance to actually commit.

On Thu, Feb 26, 2015 at 10:43 AM, Nelson Saavedra <saavedra.nelson@gmail.com
> wrote:

> You can look at who did what since the beginning of (git) times
>
> On Thu, Feb 26, 2015 at 10:42 AM, Antonio Kanaan <notifications@github.com
> > wrote:
>
>> my worry is that this disappears into history and unless somebody
>> remembers
>> it existed someday and knows what it was called we will end up redoing
>> these things in case we need them. Makes sense?
>>
>> On Thu, Feb 26, 2015 at 10:39 AM, William Schoenell <
>>
>> notifications@github.com> wrote:
>>
>> > Everything that you do on git you can rollback whenever you want. It
>> stays
>> > on the commits history.
>> >
>> > On Thu, Feb 26, 2015 at 2:02 PM Antonio Kanaan <
>> notifications@github.com>
>> > wrote:
>> >
>> > > when you remove an unused module where does it go? heaven? limbo?
>> hell?
>> > >
>> > > the reason I ask is that we may ressurrect some of these things in the
>> > > future. For instance, we talked about using the webadmin module, or
>> > > something similar to it, to close the dome in the future.
>> > >
>> > > The idea is to have the 4m operator issue some sort of broadcast
>> signal
>> > in
>> > > the ctio network informing all telescopes that the 4m is being closed
>> due
>> > > to weather conditions.
>> > >
>> > > We are going in a new direction with the GUI, still it is important to
>> > keep
>> > > some copy of it, just in case.
>> > >
>> > > A
>> > >
>> > > On Tue, Feb 24, 2015 at 11:46 AM, William Schoenell <
>> > > notifications@github.com> wrote:
>> > >
>> > > > Remove unused / not working modules.
>> > > >
>> > > > - Cherrypy
>> > > > - webadmin module
>> > > > - gui module
>> > > >
>> > > > —
>> > > > Reply to this email directly or view it on GitHub
>> > > > <https://github.com/astroufsc/chimera/issues/35>.
>> > > >
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <https://github.com/astroufsc/chimera/issues/35#issuecomment-76174204
>> >.
>> >
>> > >
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/astroufsc/chimera/issues/35#issuecomment-76179026>.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/astroufsc/chimera/issues/35#issuecomment-76179430>.
>>
>
>
>
> --
> Nelson Saavedra Pinos
> ------------------------------------------------
> NAIR Servicios Informáticos E.I.R.L.
> ------------------------------------------------
> e: saavedra.nelson@gmail.com
> c: +56 51 69074027
>



-- 
Nelson Saavedra Pinos
------------------------------------------------
NAIR Servicios Informáticos E.I.R.L.
------------------------------------------------
e: saavedra.nelson@gmail.com
c: +56 51 69074027

**Comment by wschoenell** [comment]
We have this issue that will be saved for the records even if closed.
We can annotate the commit/PR where we deleted this thing. For
example: 979f63303b85d6d9dc4cde32f890ddcbd76d8be2 will redirect to the last
commit right now on the repo.

**Comment by wschoenell** [comment]
Cleaning done on #113, #86, #85, #84, #76, #75, #70, #65, #62, #61, #60 and #54
