### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by tribeiro** [astroufsc/chimera#37]
After observing for most of the night (doing some fast-tracking tests so, lots of images!) I got the following error message after taking an exposure. 

```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/chimera_python-0.2.dev-py2.7.egg/EGG-INFO/scripts/chimera-cam", line 579, in expose
object_name=object_name)
File "/usr/local/lib/python2.7/dist-packages/chimera_python-0.2.dev-py2.7.egg/chimera/core/proxy.py", line 109, in __call__
return self.sender(self.method, args, kwargs)
File "/usr/local/lib/python2.7/dist-packages/Pyro-3.16-py2.7.egg/Pyro/core.py", line 456, in _invokePYRO
return self.adapter.remoteInvocation(name, Pyro.constants.RIF_VarargsAndKeywords, vargs, kargs)
File "/usr/local/lib/python2.7/dist-packages/Pyro-3.16-py2.7.egg/Pyro/protocol.py", line 497, in remoteInvocation
return self._remoteInvocation(method, flags, *args)
File "/usr/local/lib/python2.7/dist-packages/Pyro-3.16-py2.7.egg/Pyro/protocol.py", line 572, in _remoteInvocation
answer.raiseEx()
File "/usr/local/lib/python2.7/dist-packages/Pyro-3.16-py2.7.egg/Pyro/errors.py", line 72, in raiseEx
raise self.excObj
OSError: [Errno 24] Too many open files
+--- Remote traceback:
| Traceback (most recent call last):
| File "C:\Users\camera\AppData\Local\Continuum\Anaconda\lib\site-packages\pyro-3.16-py2.7.egg\Pyro\protocol.py", line 759, in _handleInvocation2
| res = obj.Pyro_dyncall(req[1],flags,req[3]) # (method,flags,args)
| File "C:\Users\camera\AppData\Local\Continuum\Anaconda\lib\site-packages\chimera_python-0.2.dev_r0-py2.7.egg\chimera\core\remoteobject.py", line 96, in Pyro_dyncall
| return getattr(self, method)(*args, **keywords)
| File "C:\Users\camera\AppData\Local\Continuum\Anaconda\lib\site-packages\chimera_python-0.2.dev_r0-py2.7.egg\chimera\core\methodwrapper.py", line 112, in __call__
| return self.call(self.instance, *args, **kwargs)
| File "C:\Users\camera\AppData\Local\Continuum\Anaconda\lib\site-packages\chimera_python-0.2.dev_r0-py2.7.egg\chimera\core\lockwrapper.py", line 66, in call
| ret = self.func(*args, **kwargs)
| File "C:\Users\camera\AppData\Local\Continuum\Anaconda\lib\site-packages\chimera_python-0.2.dev_r0-py2.7.egg\chimera\instruments\camera.py", line 62, in expose
| return self._baseExpose(request, **kwargs)
| File "C:\Users\camera\AppData\Local\Continuum\Anaconda\lib\site-packages\chimera_python-0.2.dev_r0-py2.7.egg\chimera\instruments\camera.py", line 121, in _baseExpose
| image = self._readout(imageRequest)
| File "C:\Users\camera\AppData\Local\Continuum\Anaconda\lib\site-packages\chimera_python-0.2.dev_r0-py2.7.egg\chimera\instruments\fli\fli.py", line 343, in _readout
| "binning_factor": self._binning_factors[binning]})
| File "C:\Users\camera\AppData\Local\Continuum\Anaconda\lib\site-packages\chimera_python-0.2.dev_r0-py2.7.egg\chimera\instruments\camera.py", line 210, in _saveImage
| img.compress(multiprocess=True)
| File "C:\Users\camera\AppData\Local\Continuum\Anaconda\lib\site-packages\chimera_python-0.2.dev_r0-py2.7.egg\chimera\util\image.py", line 398, in compress
| p.start()
| File "C:\Users\camera\AppData\Local\Continuum\Anaconda\lib\multiprocessing\process.py", line 130, in start
| File "C:\Users\camera\AppData\Local\Continuum\Anaconda\lib\multiprocessing\forking.py", line 273, in __init__
| OSError: [Errno 24] Too many open files
+--- End of remote traceback
Error trying to take exposures. (None)
```

Had to "reboot" chimera to be able to take exposures again. The error was issue during "reading out and saving..."

**Comment by phsilva** [comment]
Interesting.... next time, before restarting chimera, run:
```bash
lsof -p <pid-of-chimera>
```
and past it here so we can see.
My main suspect is that we are not closing sockets on callback or something like that, so we end up having tons of open sockets laying around. Will try to test it.

BTW, are you using astroufsc/chimera master on your night tests? just curious about the stability.

**Comment by tribeiro** [comment]
Ok. It will probably be awhile before we have another run that take that many exposure but I will keep this in mind. 

> BTW, are you using astroufsc/chimera master on your night tests? just curious about the stability.
> 
I am actually a couple of commits ahead. Some of the things I implemented on astelco.py worked on the benchmark telescope astelco provide to us but where not working in real life. Specially the waitSlew operation. But I ended up discovering another bug on both earlier and newer version that would prevent the slew  operation to complete. I managed to fix that as well. 

Something that I also discovered and I think may be a bug on astelo,is that, if you open 4 tpl connections the server will go down. Even their GUI loose connection. I could not, in the heat of the moment, take screen shots but I will do that next time. Anyway, the tpl implementation was unable to bring the connection back once it breaks. I did implemented that new feature now. Meaning that, if you try to connect and the connection is closed, it tries to reopen it. If it fails to reopen it still keep the instrument alive and try again next time. I think this is better than hanging up on a connection that may never come alive again. 

I also implemented the missing offset feature (#34). They worked pretty good so far. 

All and all, the version I am running now proved to be much more reliable. Prove is it was kept alive long enough to generate the “too many open files”.  I am now reviewing the points you raised about my code revision and will do a PR once it is ready and tested. Let me know if you have any suggestions about what should be tested and how. 

Cheers, 

T.

**Comment by phsilva** [comment]
Nice!

**Comment by phsilva** [comment]
I found the too many open files issue. We never close the Image objects on chimera-cam. On readoutComplete callback we get a Proxy for the Image, no files open on this side, but on the other side there is the real Image instance with a live pyfits file still open.

I am not sure if the right way is this, but I added a close method on Image and now chimera-cam calls it after he uses the Image Proxy.

**Comment by tribeiro** [comment]
Great! That was really quick! 

Cheers, 

T.
