### ISSUE TITLE
[chimera-dome] fails with --track option

### ISSUE THREAD

**Issue by wschoenell** [astroufsc/chimera#39]
chimera-dome fails when trying to set chimera-dome to track the telescope.

	(chimera)Williams-MacBook-Pro:~ william$ chimera-dome --info
	======================================== 
	Dome: /FakeDome/fake (/dev/ttyS1). 
	Current dome azimuth: 0.00. 
	Current dome mode: None. 
	Dome slit is closed. 
	======================================== 
	(chimera)Williams-MacBook-Pro:~ william$ chimera-dome --track
	Something wrong with 'track' action. 
	Traceback (most recent call last):
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/chimera/core/cli.py", line 740, in _runAction
		method(options)
	  File "/Users/william/.virtualenvs/chimera/bin/chimera-dome", line 91, in track
		self.dome["telescope"] = options.telescope
	TypeError: 'Proxy' object does not support item assignment

	(chimera)Williams-MacBook-Pro:~ william$ chimera-dome --stand
	Deactivating tracking ...  OK 
	(chimera)Williams-MacBook-Pro:~ william$ chimera-dome --track
	Something wrong with 'track' action. 
	Traceback (most recent call last):
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/chimera/core/cli.py", line 740, in _runAction
		method(options)
	  File "/Users/william/.virtualenvs/chimera/bin/chimera-dome", line 91, in track
		self.dome["telescope"] = options.telescope
	TypeError: 'Proxy' object does not support item assignment
	(chimera)Williams-MacBook-Pro:~ william$ chimera-dome --info
	======================================== 
	Dome: /FakeDome/fake (/dev/ttyS1). 
	Current dome azimuth: 359.11. 
	Current dome mode: Stand. 
	Dome slit is closed. 
	========================================

**Comment by tribeiro** [comment]
I have a fix for this. I though it was on my last PR but it wasn't... I will check it tomorrow...

**Comment by wschoenell** [comment]
Thanks! Please do a PR just for this. Let's do smaller PRs :-)

**Comment by wschoenell** [comment]
Fixed by PR #42
