### ISSUE TITLE
chimera-filter not working

### ISSUE THREAD

**Issue by tribeiro** [astroufsc/chimera#44]
When you try to change the filter via chimera-filter script it aways gives "Invalid filter"... @nsaavedra-naircl and I figured the problem in line 96

```python
if self.options.filtername and filter not in self.wheel.getFilters():
```

where it is looking if self.options.filtername is set (which is already done at parsing level) and them comparing a python built-in function "filter" with a list of filters. Changing this line to:

```python
if self.options.filtername not in self.wheel.getFilters():
```

fixes the issue.

**Comment by phsilva** [comment]
buggy, yes.
