### ISSUE TITLE
Different SI drivers for "camera" and "polarimeter"

### ISSUE THREAD

**Issue by tribeiro** [astroufsc/chimera#45]
While reviewing @nsaavedra-naircl driver today we noticed that the filterwheel is implemented as part of camera. This actually makes a lot of sense to me so I propose we develop two separate instruments for the SI at the T80.

SICamera -> which inherits FsuFilters: This is the Camera+Filter wheel, which will be used for normal operations.

SICameraPol -> which inherits FSUPolarizer and FSUWavePLate: Which will be used when the polarimeter is installed.

Even though they use the same (SI) camera they are actually two different (and incompatible) instruments. Meaning that, you cannot use one mode at the same time as the other. This way we simulate the physical operation of changing the wheels by the polarizer and wave plate within chimera.

Also, we could have the driver for the SI camera separated, as @nsaavedra-naircl is already developing it, and SICamera and SICameraPol inherits it. This will avoid unnecessarily replication of code.

**Comment by wschoenell** [comment]
This is being discussed on astroufsc/chimera-t80cam#1 . I think that we can close this issue since we plan to separate the filter wheel (and hence the polarizer) from the camera.
