### ISSUE TITLE
[PROPOSAL] chimera header/metadata standardization

### ISSUE THREAD

**Issue by wschoenell** [astroufsc/chimera#50]
The way that chimera now gets the image headers to compose the image is to ask each location registered on the Proxy its metadata. Then, the metadata can come from the instrument base or the driver itself.

https://github.com/astroufsc/chimera/blob/9f4689a5d514893e8571595b9f05ff667e8b1919/src/chimera/controllers/imageserver/imagerequest.py#L148-L159

My suggestion is to lock on each instrument base object (i.e. TelescopeBase, CameraBase, ...) the instrument mandatory header keywords (at least for chimera) and then, for each driver, create a set of hierarchical keywords (like ESO HIERARCHICAL, [1]) where each driver along the chain, having its own characteristics, would add the HIERARCH set of keywords.

I confess that I am still not very happy with this distribution of keywords along the code with the getMetadata methods being overwritten by higher instances but this is the only way that I could think how pass the metadata info along the chain of instruments in a more flexible way.

[1] http://archive.eso.org/cms/tools-documentation/eso-data-interface-control.html

**Comment by nsaavedra-naircl** [comment]
I have an opinion on this topic, but will not express it unless asked, and I’m not sure if doing it in this venue is right?

Nelson Saavedra Pinos
------------------------------------------------
NAIR Servicios Informáticos E.I.R.L.
------------------------------------------------
e: saavedra.nelson@gmail.com
c: +56 51 69074027

**Comment by wschoenell** [comment]
Spit it. We live in a democratic Universe.

**Comment by wschoenell** [comment]
I think that the most updated and broad fits keyword naming standard nowadays is the one provided by ESO. It haves the standard basic keywords well defined and a set of many others that are non-standard and we will probably need on a near future with the T80. I would go for standardizing the naming of the headers with this format.

http://archive.eso.org/cms/tools-documentation/eso-data-interface-control.html
