### ISSUE TITLE
[PROPOSAL] Changes to the install procedure (setup.py)

### ISSUE THREAD

**Issue by nsaavedra-naircl** [astroufsc/chimera#56]
Lately Chimera has been in need to incorporate packages, modules, libs, etc., that are not as much in PyPi as they reside in repos like github. Examples are the SI drivers, the AVT libraries and APIs, and the FLI camera lib. So far we have been either doing manual installs from each packages setup.py, or incorporating the code within the chimera structure.
The easiest  (imho) way to support this would be to use the "dependency_links" feature of setuptools. Another way would be to use git submodules, but I think this is less straightforward for non git savvy users.

**Comment by wschoenell** [comment]
+1 for this. I was blaming just today that we have too much requirements that sometimes are unnecessary for a simple install.

**Comment by phsilva** [comment]
Not sure dependency_links is what we really need. What we need is a way to specify optional dependencies based on the intended features.

One solution is have separate repositories for separate functionally in this case. like: chimera-sbig, chimera-fli, chimera-si and so on. This way we can leave the dependencies in the right place but without asking users to install too much stuff manually. Of course, only If we can find a way to have those independent packages in a easily installable way.

Use of git submodules in this case is not necessary.

Chimera already supports this way of thinking. If you have a chimera-sbig package, which installs itself in a package names chimera.instruments.sbig, the chimera-core module will find it as it will be available in chimera classloader package. It is a matter f trying, maybe the chimera-fli is the first one, followed by sbig, probably.

**Comment by phsilva** [comment]
pip install chimera-core
pip install chimera-sbig
pip install chimera-fli
pip install chimera-meade

doesn't look too bad for me.

**Comment by wschoenell** [comment]
Something like this, you say?

https://www.python.org/dev/peps/pep-0420/#namespace-packages-today

**Comment by phsilva** [comment]
It could be, but can be even simpler: we change Chimera's classloader to load anything from any package. Today, when you try to load an instrument we always look at it at chimera.instruments.XXX, if we remove this restriction, any package installed could be treated as a Chimera instrument/controller and so on.

**Comment by wschoenell** [comment]
So... I did some tests and I think that we could search inside all packages named chimera_??? for instrument/controllers and add them to the path. What you think?

My suggestion is to do these changes (link below) to the code so all chimera_(pluginname)/(instruments|controllers)/ directories are automatically added to the corresponding paths.
https://github.com/astroufsc/chimera/compare/master...wschoenell:chimera_plugins

I've created an chimera_template plugin to test it.
https://github.com/astroufsc/chimera_template

The way to test:

	pip install -U --no-deps git+https://github.com/astroufsc/chimera_template.git
	pip install -U --no-deps git+https://github.com/wschoenell/chimera.git@chimera_plugins
	chimera -vvvvvvv -i /InstrumentExample/inst -i /ControllerExample/cont
   
This should be print among other stuff something like:

	19-05-2015 19:51:57.857 [localhost:7666] INFO chimera.controllers.site.main main.py:233 Trying to start instruments...
	...
	19-05-2015 19:52:03.311 [localhost:7666] INFO chimera.core.manager manager.py:530 Starting /InstrumentExample/inst.
	19-05-2015 19:52:03.312 [localhost:7666] WARNING chimera.instrumentexample (instrumentexample) instrumentexample.py:16 Hi, I'm doing something.
	19-05-2015 19:52:03.313 [localhost:7666] WARNING chimera.instrumentexample (instrumentexample) instrumentexample.py:17 My arg=test argument
	19-05-2015 19:52:03.313 [localhost:7666] WARNING chimera.instrumentexample (instrumentexample) instrumentexample.py:18 My param1=a string parameter
	19-05-2015 19:52:03.313 [localhost:7666] INFO chimera.core.manager manager.py:547 Running /InstrumentExample/inst. __main___.
	...
	19-05-2015 19:52:03.314 [localhost:7666] INFO chimera.controllers.site.main main.py:241 Trying to start controllers...
	...
	19-05-2015 19:52:03.344 [localhost:7666] WARNING chimera.controllerexample (controllerexample) controllerexample.py:16 Hi, I'm doing something.
	19-05-2015 19:52:03.344 [localhost:7666] WARNING chimera.controllerexample (controllerexample) controllerexample.py:17 My arg=test argument
	19-05-2015 19:52:03.345 [localhost:7666] WARNING chimera.controllerexample (controllerexample) controllerexample.py:18 My param1=a string parameter
	19-05-2015 19:52:03.345 [localhost:7666] INFO chimera.core.manager manager.py:547 Running /ControllerExample/cont. __main___.
	...
