### ISSUE TITLE
Problem with multiple connections on TPL server

### ISSUE THREAD

**Issue by tribeiro** [astroufsc/chimera#59]
After experiencing a lot of problems with the tpl connection in the current framework I started to dig around trying to figure out what the problem could be. After some days experiencing with it, I think I discovered what the problem is. Lets say you have 2 connections on TPL, one for the telescope and one for the dome. The telescope sends a request for some value (say telescope azimuth), shortly after the dome does the same, asking the azimuth of the dome. In this case you have two connections, each generate a single command ID. Now, if the dome asks for a response first, it may (or may not, this is a concurrency problem) receive the response that was target for the telescope instead. In this case, the dome receives an answer that doesn't make sense at all for him. At the same time, the telescope will hang around with no answer to its request, or will receive the answer that was targeted for the dome. 

I think the solution for this is to go back to the idea of a single TPL channel, as a chimera instrument. Any thoughts/suggestions?

**Comment by tribeiro** [comment]
After a more careful look, I think this is not the issue after all. The bad ids that I'm getting are completely unrelated...

**Comment by ankanaan** [comment]
how come?

did you fix this?  what is the fix?

**Comment by ankanaan** [comment]
ok, sorry :-)

**Comment by wschoenell** [comment]
Is this still an issue? If so, let's move it to astroufsc/chimera-astelco . Otherwise we close it.

**Comment by tribeiro** [comment]
That is fixed on the new driver.

Em quinta-feira, 16 de julho de 2015, William Schoenell <
notifications@github.com> escreveu:

> Is this still an issue? If so, let's move it to astroufsc/chimera-astelco
> . Otherwise we close it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/astroufsc/chimera/issues/59#issuecomment-121984319>.
>


-- 
Sent from Mobile

**Comment by wschoenell** [comment]
So I close it.
