### ISSUE TITLE
WCS information not compatible with WCSLIB

### ISSUE THREAD

**Issue by tribeiro** [astroufsc/chimera#73]
If I try to open the wcs information from an image saved with chimera I get "Unrecognized projection code (-TA in CTYPE2)." error. The CTYPE2 keyword has entry "DEC---TA". It looks like the right format is "DEC--TA", with one less "-".

**Comment by phsilva** [comment]
wcs paper I states (http://fits.gsfc.nasa.gov/fits_wcs.html):

"Non-linear coordinate systems will be signaled by CTYPEi in “4–3” form:
the first four characters specify the coordinate type, the fifth character
is a ’-’, and the remaining three characters specify an algorithm code for
computing the world coordinate value, for example ’ABCD-XYZ’. We explicitly
allow the possibility that the coordinate type may augment the algorithm
code, for example ’FREQ-F2W’ and ’VRAD-F2W’ may denote somewhat different
algorithms (see Paper III). *Coordinate types with names of less than four
characters are padded on the right with ’-’, and algorithm codes with less
than three characters are padded on the right with blanks, for example
’RA---UV ’.*"

So the format is alright, but the project TA does not exists, the right is
TAN, so it should be DEC-*-*TAN and RA--*-*TAN, probably readers used to be
promiscuous and allowed TA to be interpreted as TAN, but it is definitely
wrong.


2015-07-14 1:12 GMT-03:00 Tiago <notifications@github.com>:

**Comment by phsilva** [comment]
https://github.com/astroufsc/chimera/blob/master/src/chimera/instruments/telescope.py#L238 is correct, TAN projection. Where did you get this -TA header?

**Comment by phsilva** [comment]
no, https://github.com/astroufsc/chimera/blob/master/src/chimera/instruments/telescope.py#L238 is not right, the "-" padding is wrong, dammit. CTYPE1 is alright but CTYPE2 is wrong.

**Comment by tribeiro** [comment]
Yes, I was about to write that... :-)


T.

**Comment by phsilva** [comment]
fixed by #74
