### ISSUE TITLE
Problem with sextractor

### ISSUE THREAD

**Issue by tribeiro** [astroufsc/chimera#80]
There is a strange problem with sextractor. It works on numeral occasions but, If I change something on the image request and take another shot it will fail with a

> *Error*: cannot open "IMAGE NAME"

I though of a way of fixing it, by checking that the image exists before running the procedure. If the image does not exists it will write the image and go ahead.

**Comment by wschoenell** [comment]
Is this error reproducible somehow or it does happens randomly?
If it is the second option, I think that what is happening is that when you call `extract()`, the `save()` that you called just before wasn't finished yet. So the fix would be wait the file creation between `save()` and `extract()` call or put a lock when calling `save()` where it does not goes to `extract()` until the file is not entirely saved. What you think?

**Comment by wschoenell** [comment]
Fixed on #91.
